# Generated by Django 4.2.3 on 2023-07-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallerdb', '0004_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
